import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Plants from './components/Plants'

export default function Home() {
  return (
    <div classNameName={styles.container}>
      <Head>
        <title>Mother&apos;s Garden</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <h1>
          <span className="italic">Mother&apos;s</span> Garden.
        </h1>
        <section className="grid">
          {/* <!-- Column 1 --> */}
          <div className="grid-column">
            <Plants/>
          </div>
        </section>
      </main>
    </div>
  );
}
