import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/utils.module.scss';
import Plants from './components/Plants';
import { MainContainer } from '../styles/styles';
import HeaderContainer from './components/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mother&apos;s Garden</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MainContainer>
        <HeaderContainer />
        <Plants />
      </MainContainer>
    </div>
  );
}
